- name: Install Docker
  yum:
    name: docker
    state: present

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Copy custom HTML page
  copy:
    src: index.html
    dest: /home/ec2-user/index.html

- name: Run Nginx container
  docker_container:
    name: nginx
    image: nginx
    state: started
    restart_policy: always
    ports:
      - "80:80"
    volumes:
      - /home/ec2-user/index.html:/usr/share/nginx/html/index.html:ro
